/** Seed data for the vocabulary dimensions: a common-acronym allowlist and US/UK spelling pairs. */

/** Acronyms so common they need no definition. Extendable per profile via `options.allowlist`. */
export const ACRONYM_ALLOWLIST: ReadonlyArray<string> = [
  "API",
  "URL",
  "URI",
  "HTTP",
  "HTTPS",
  "JSON",
  "YAML",
  "XML",
  "HTML",
  "CSS",
  "SQL",
  "REST",
  "CLI",
  "GUI",
  "ID",
  "OK",
  "FAQ",
  "PDF",
  "CSV",
  "UI",
  "UX",
  "IDE",
  "NPM",
  "CPU",
  "GPU",
  "RAM",
  "OS",
  "IO",
  "TLS",
  "SSL",
  "DNS",
  "IP",
  "TCP",
  "UDP",
  "SDK",
  "CI",
  "CD",
  "AI",
  "ML",
  "LLM",
  "MCP",
  "USB",
  "PDF",
  "URL",
  "ISO",
  "UTC",
  "USA",
  "UK",
  "EU",
  "FYI",
  "ASAP",
  "AKA",
  "ETC",
  "MIT",
  "GPL",
  "BSD",
  "LTS",
  "GNU",
  // Common all-caps words that are not acronyms.
  "README",
  "TODO",
  "FIXME",
  "NOTE",
  "WARNING",
]

/** US/UK spelling pairs, `[usForm, ukForm]`, lower-cased. */
export const US_UK_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["color", "colour"],
  ["honor", "honour"],
  ["favor", "favour"],
  ["flavor", "flavour"],
  ["humor", "humour"],
  ["labor", "labour"],
  ["neighbor", "neighbour"],
  ["behavior", "behaviour"],
  ["center", "centre"],
  ["meter", "metre"],
  ["theater", "theatre"],
  ["liter", "litre"],
  ["fiber", "fibre"],
  ["organize", "organise"],
  ["recognize", "recognise"],
  ["analyze", "analyse"],
  ["apologize", "apologise"],
  ["catalog", "catalogue"],
  ["dialog", "dialogue"],
  ["defense", "defence"],
  ["offense", "offence"],
  ["gray", "grey"],
  ["traveled", "travelled"],
  ["canceled", "cancelled"],
  ["modeling", "modelling"],
  ["labeled", "labelled"],
  ["fulfill", "fulfil"],
  ["enroll", "enrol"],
  ["skillful", "skilful"],
  ["jewelry", "jewellery"],
  ["aluminum", "aluminium"],
  ["judgment", "judgement"],
  ["acknowledgment", "acknowledgement"],
  ["initialize", "initialise"],
  ["customize", "customise"],
  ["optimize", "optimise"],
]
